# Generated by Django 2.2 on 2022-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetables',
            name='id',
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='u_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
