# Generated by Django 2.2 on 2022-01-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220123_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetables',
            old_name='u_id',
            new_name='id',
        ),
    ]
