# Generated by Django 2.2 on 2022-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220123_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='baby',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='beverage',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='bread_bakery',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
