# Generated by Django 2.2 on 2022-01-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_baby_beverage_bread_bakery_fruits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beverage',
            new_name='babies',
        ),
        migrations.RenameModel(
            old_name='baby',
            new_name='beverages',
        ),
    ]
